Newmenu/newmenu/config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  root 'home#index'
get 'meetings/index'

  get 'meetings/show'

  get 'meetings/new'

  get 'meetings/edit'

  get 'meetings/update'
  get 'home/destroy'
  get 'home/create'
  get 'home/update'
  post "/create" => "home#create"

  devise_for :users, controllers: {registrations: "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Newmenu/newmenu/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Newmenu/newmenu/app/models/meeting.rb
class Meeting < ApplicationRecord
end

Newmenu/newmenu/app/models/order.rb
class Order < ApplicationRecord
end

Newmenu/newmenu/app/models/orders_item.rb
class OrdersItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

Newmenu/newmenu/app/models/product.rb
class Product < ApplicationRecord
end

Newmenu/newmenu/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

Newmenu/newmenu/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #before any action we need authentication from current user(need to be log in )
  before_action :authenticate_user!
  # before_action :set_time_zone, if: :user_signed_in?
 def index
  @meetings = Meeting.all
end

 private

 # def set_time_zone
 #    Time.zone = current_user.time_zone
 # end
end

Newmenu/newmenu/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

     check_data = params[:start_date]
  if(!check_data.nil?)
    @date_a = check_data
  else
    @date_a = Time.now.strftime("%Y-%m-%d")
  end
  	@meetings = Meeting.all
  	if user_signed_in?
  	else
  		redirect_to new_user_session_path
  	end
    @date_a = params[:start_date]
    @user = current_user.id

     @products_supi = Product.where(category: "supi")
     @products_osnovni = Product.where(category: "osnovni")
     @products_sandvichi = Product.where(category: "sandvichi")
     @products_deserti = Product.where(category: "deserti")
     @products_napitki = Product.where(category: "napitki")
     


     id_array = []
     @date = 0

     @products = Product.all
     id_array = []


     @for_home = 0
     @items_array =  []
     @items_array_product =  []
     @counter=0
    @counter_del=0
     @sum =0
     
      @orders = Order.where(user_id: @user,date:@date_a ).all
      @orders.each do |order_id|
          id_array = id_array.push(order_id.id)
      end
  
     @order_items =  OrdersItem.where(order_id:  id_array).all
  
    @order_items.each do |order_items_id|
      @items_array = @items_array.push(order_items_id.id)
    end
      @order_items.each do |order_items_product|
       @items_array_product = @items_array_product.push(order_items_product.product_id)

     end
     
     
        @current_products = Product.where(id: @items_array_product)
    
     @order_items.each do |order_items_total_sum|
      @sum = @sum +order_items_total_sum.total_price
      end

  end


  def home
  	@meetings = Meeting.all
  end
  def item_params
  params.require(:selected_product_id).permit(:value)
  end


  def create
    total_price = 0
    if(params[:for_home]) 
      for_home =(params[:for_home].gsub(/[^0-9]/, '')).to_i
    end
      if(for_home == 1)
        for_home = 1
    
      else
        for_home = 0
      end



      date = params[:date]



     quantity = params[:quantity].to_i
       description =params[:description]
      create_this_user_order = current_user.id 
      product_price = Product.where(id: @items_array_product).all
 
     
    
       create_this_product_id = (params[:product_id].gsub(/[^0-9]/, '')).to_i
       product_price = Product.where(id: create_this_product_id).first
       
         total_price = product_price.price* quantity
      

      

      object_order = Order.new(:user_id => create_this_user_order,:date => date)
      object_order.save
     select_last_order_id = Order.last.id
     object_orders_item = OrdersItem.new(:product_id => create_this_product_id , :order_id =>  select_last_order_id ,:quantity => quantity,:description => description ,:date => date,:for_home =>for_home,:total_price => total_price,:date => date )
     object_orders_item.save
     redirect_to '/'
  end
  def update
    current_product_price = params[:product_price].to_f
    order_item_id_update = params[:order_item_id_update]
    get_less = params[:less].to_i
    get_add = params[:add].to_i
    if(get_add >= 1)
        update_order_item_quantity = OrdersItem.find_by(id: order_item_id_update)
        add_to_quantity = get_add + 1
        update_total_price = current_product_price*add_to_quantity
        update_order_item_quantity.update(quantity: add_to_quantity,total_price: update_total_price)
      else
        if(get_less > 1)
        update_order_item_quantity = OrdersItem.find_by(id: order_item_id_update)
        less_to_quantity = get_less - 1
         update_total_price = current_product_price*less_to_quantity

        update_order_item_quantity.update(quantity: less_to_quantity,total_price: update_total_price)
      end
      end


       redirect_to '/'
  end
  def new

  end
  def destroy
    this_user = current_user.id
    

    delete_this_id = params[:id]
    delete_current_product_order_items_id  = params[:current_product_order_items_id]
  
     OrdersItem.where(product_id: delete_this_id,id: delete_current_product_order_items_id).destroy_all
    Order.where(id: delete_current_product_order_items_id,user_id: this_user).destroy_all
   
    
    
     redirect_to '/'
  end
  def show
  end

  def help
  end

  def about
  end
end

Newmenu/newmenu/app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    @meetings = Meeting.all
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:name, :start_time, :end_time)
    end
end

Newmenu/newmenu/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

	def account_update_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
	end
end

Newmenu/newmenu/app/helpers/application_helper.rb
module ApplicationHelper
end

Newmenu/newmenu/app/helpers/home_helper.rb
module HomeHelper
end

Newmenu/newmenu/app/helpers/meetings_helper.rb
module MeetingsHelper
end

Newmenu/newmenu/app/views/home/index.html.erb
  <div class="row">
<<<<<<< HEAD
<%=  @date_a %>
=======
    <%= @date_a %>


>>>>>>> 1f7cbfb0b7aff569e305ad21f7b349dd2cd32965
<h2> Поръчано за деня</h2>
    <div class="row" style="border-top:1px solid black">
       
       <%  @order_items.each do |current_order_item| %>
                     <%  @current_products.each do |current_product| %>
                     <% if(current_product.id == current_order_item.product_id) %>
      <div class="col-lg-6 portfolio-item">
          <div class="card h-100">
           
              <a href="#"><%=image_tag("#{current_product.id}.jpg", alt: "Example Image", class: :imgpr)%></a>
               <div class="card-body">
              <h4 class="card-title">
    <a href="#" style="border: solid 10px; border-color: #f1f1f1"><%= current_product.name%></a>
    <p><%= current_product.description %></p>


</h4>
       <p href="#" style="border: solid 10px; border-color: #f1f1f1"> <%=     number_with_precision(current_product.price, :precision => 2) %> лв.</p>
        <% current_product.id %>
          <% current_product_order_items_id  = @items_array[@counter] %>
          <% @counter=@counter+1 %>

         </div>
          <p> <%= link_to "Откажи",{:controller => :home,:action => 'destroy',:id => current_product.id ,:current_product_order_items_id =>  current_product_order_items_id},data: {confirm: 'Сигурни ли сте че искате да откажете тази поръчка?'} %> </p>
       </div>
     </div>

        
    <% end %>
 <% end %>
    <% end %>
    <% if(@counter==0) %>
     <div class="col-lg-6 portfolio-item">
          <div class="card h-100">
    <h1> Нямате поръчка </h1>
  </div>
</div>
    <% end %>
     </div>

   
 
       <h2> Ястия </h2>
 <div class="row" style="border-top:1px solid black">
<<<<<<< HEAD
      <h3>  Супи</h3>
         
          <% @products_supi.each do |product| %>
           <div class="col-lg-6 portfolio-item">
          <div class="card h-100">
      
              <a href="#"><%=image_tag("#{product.id}.jpg", alt: "Example Image", class: :imgpr)%></a>
               <div class="card-body">
              <h4 class="card-title">
    <a href="#" style="border: solid 10px; border-color: #f1f1f1"><%= product.name %></a>
    <p> <%= product.description %> </p>
</h4>
       <p class="card-text" style="border: solid 10px; border-color: #f1f1f1">Цена: <%= number_with_precision(product.price, :precision => 2) %>.лв</p>
         <%= form_tag('/create') do%>
          <%= label_tag :Предпочитания %>
         <%= text_field_tag(:description, params[:description],class: 'form-control')  %>
       </br><%= label_tag :Количество %>
            <%= number_field_tag( :quantity , params[:quantity], value:1 , min: 1, max:10 ,class: 'form-control') %>
            
            <%= hidden_field_tag :product_id , :value => product.id %>
            <%= hidden_field_tag :date , :value => @date_a %>

          </br>
            <%= check_box_tag :for_home,class: 'form-check-input'  %>
              <%= label_tag(:for_home, "За вкъщи") %>
              </div>



=======
>>>>>>> 1f7cbfb0b7aff569e305ad21f7b349dd2cd32965

         
          <% @products.each do |product| %>
           <div class="col-lg-6 portfolio-item">
          <div class="card h-100">
      
              <a href="#"><%=image_tag("#{product.id}.jpg", alt: "Example Image", class: :imgpr)%></a>
               <div class="card-body">
              <h4 class="card-title">
    <a href="#" style="border: solid 10px; border-color: #f1f1f1"><%= product.name %></a>
    <p> <%= product.description %> </p>
</h4>
       <p class="card-text" style="border: solid 10px; border-color: #f1f1f1">Цена: <%=  number_with_precision(product.price, :precision => 2)  %>.лв</p>
         <%= form_tag('/create') do%>
          <%= label_tag :Предпочитания %>
         <%= text_field_tag(:description, params[:description],class: 'form-control')  %>
       </br><%= label_tag :Количество %>
            <%= number_field_tag( :quantity , params[:quantity], value:1 , min: 1, max:10 ,class: 'form-control') %>
<<<<<<< HEAD
            <%= hidden_field_tag :product_id , :value => product.id %>
            <%= hidden_field_tag :date , :value => @date_a %>

          </br>
            <%= check_box_tag :for_home,class: 'form-check-input'  %>
              <%= label_tag(:for_home, "За вкъщи") %>
              </div>





              <%= submit_tag "Поръчай" %>
              <% end %>
                </div>
     </div>
             <% end %>
   </div>


<div class="row" style="border-top:1px solid black">
      <h3> Сандвичи</h3>
         
          <% @products_sandvichi.each do |product| %>
           <div class="col-lg-6 portfolio-item">
          <div class="card h-100">
      
              <a href="#"><%=image_tag("#{product.id}.jpg", alt: "Example Image", class: :imgpr)%></a>
               <div class="card-body">
              <h4 class="card-title">
    <a href="#" style="border: solid 10px; border-color: #f1f1f1"><%= product.name %></a>
    <p> <%= product.description %> </p>
</h4>
       <p class="card-text" style="border: solid 10px; border-color: #f1f1f1">Цена: <%= number_with_precision(product.price, :precision => 2) %>.лв</p>
         <%= form_tag('/create') do%>
          <%= label_tag :Предпочитания %>
         <%= text_field_tag(:description, params[:description],class: 'form-control')  %>
       </br><%= label_tag :Количество %>
            <%= number_field_tag( :quantity , params[:quantity], value:1 , min: 1, max:10 ,class: 'form-control') %>
            
            <%= hidden_field_tag :product_id , :value => product.id %>
            <%= hidden_field_tag :date , :value => @date_a %>
          </br>
            <%= check_box_tag :for_home,class: 'form-check-input'  %>
              <%= label_tag(:for_home, "За вкъщи") %>
              </div>





              <%= submit_tag "Поръчай" %>
              <% end %>
                </div>
     </div>
             <% end %>
   </div>


<div class="row" style="border-top:1px solid black">
      <h3>Десерти </h3>
         
          <% @products_deserti.each do |product| %>
           <div class="col-lg-6 portfolio-item">
          <div class="card h-100">
      
              <a href="#"><%=image_tag("#{product.id}.jpg", alt: "Example Image", class: :imgpr)%></a>
               <div class="card-body">
              <h4 class="card-title">
    <a href="#" style="border: solid 10px; border-color: #f1f1f1"><%= product.name %></a>
    <p> <%= product.description %> </p>
</h4>
       <p class="card-text" style="border: solid 10px; border-color: #f1f1f1">Цена: <%= number_with_precision(product.price, :precision => 2) %>.лв</p>
         <%= form_tag('/create') do%>
          <%= label_tag :Предпочитания %>
         <%= text_field_tag(:description, params[:description],class: 'form-control')  %>
       </br><%= label_tag :Количество %>
            <%= number_field_tag( :quantity , params[:quantity], value:1 , min: 1, max:10 ,class: 'form-control') %>
            
            <%= hidden_field_tag :product_id , :value => product.id %>
            <%= hidden_field_tag :date , :value => @date_a %>
          </br>
            <%= check_box_tag :for_home,class: 'form-check-input'  %>
              <%= label_tag(:for_home, "За вкъщи") %>
              </div>





              <%= submit_tag "Поръчай" %>
              <% end %>
                </div>
     </div>
             <% end %>
   </div>


<div class="row" style="border-top:1px solid black">
      <h3> Напитки</h3>
         
          <% @products_napitki.each do |product| %>
           <div class="col-lg-6 portfolio-item">
          <div class="card h-100">
      
              <a href="#"><%=image_tag("#{product.id}.jpg", alt: "Example Image", class: :imgpr)%></a>
               <div class="card-body">
              <h4 class="card-title">
    <a href="#" style="border: solid 10px; border-color: #f1f1f1"><%= product.name %></a>
    <p> <%= product.description %> </p>
</h4>
       <p class="card-text" style="border: solid 10px; border-color: #f1f1f1">Цена: <%= number_with_precision(product.price, :precision => 2) %>.лв</p>
         <%= form_tag('/create') do%>
          <%= label_tag :Предпочитания %>
         <%= text_field_tag(:description, params[:description],class: 'form-control')  %>
       </br><%= label_tag :Количество %>
            <%= number_field_tag( :quantity , params[:quantity], value:1 , min: 1, max:10 ,class: 'form-control') %>
            
            <%= hidden_field_tag :product_id , :value => product.id %>
            <%= hidden_field_tag :date , :value => @date_a %>
          </br>
            <%= check_box_tag :for_home,class: 'form-check-input'  %>
              <%= label_tag(:for_home, "За вкъщи") %>
        
=======
            
            <%= hidden_field_tag :product_id , :value => product.id  %>
            <%= hidden_field_tag :date , :value => @date_a %>


          </br>
            <%= check_box_tag :for_home,class: 'form-check-input'  %>
              <%= label_tag(:for_home, "За вкъщи") %>
         


>>>>>>> 1f7cbfb0b7aff569e305ad21f7b349dd2cd32965
              </div>






              <%= submit_tag "Поръчай" %>
              <% end %>
                </div>
     </div>
             <% end %>
   </div>






      </div>
     

Newmenu/newmenu/app/views/layouts/_footer.html.erb
<footer class="py-5 bg-dark" style="border-style: solid;">
      <div class="container" style="border-style: solid;">
        <p class="m-0 text-center text-white">Copyright &copy; Datecs LTD 2018</p>
      </div>
      <!-- /.container -->
    </footer>

Newmenu/newmenu/app/views/layouts/_header.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded" role="navigation" ">
     <div class="container" id="navfluid" >
       <div class="navbar-header">
       <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigationbar">
       <span class="sr-only">Toggle navigation</span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
      </button>
     <%= link_to image_tag("Asset4.png", :border=>0, :class => 'logo'), root_url %>
    </div>
<div class="collapse navbar-collapse" id="navigationbar">
    <ul class="nav navbar-nav" id="menu_navbar">
      <% if user_signed_in? %>
      
        <li>
<<<<<<< HEAD
<%= calendar number_of_days: 1  do |date| %>
  <%= date %>
<% end %>
=======
      <%= calendar number_of_days: 1  do |date| %>
        <%= date %>
      <% end %>
>>>>>>> 1f7cbfb0b7aff569e305ad21f7b349dd2cd32965

        </li>
     
             <li> 
              <div id="menu_date">
               <a id="href_style_navbar" > &nbsp &nbsp &nbsp &nbsp &nbspМеню 30.02 &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp| &nbsp 5</a></div>  
               <ul>
                <li class="dropdown" style="list-style-type: none;">
                   <a href="#" class="dropdown-toggle" data-toggle="dropdown" >
               <%= current_user.name %>   </li>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li> <%= link_to "Sign out",  destroy_user_session_path, :method => 'delete' , id:'href_style_navbar_name'  %> 
              </li>
            </ul>
            </li>
          </ul>
               <% end %>
            </ul>
</div>
</div>
</nav>

Newmenu/newmenu/app/views/layouts/_menu_content.html.erb
  <!-- <div class="col-sm-8" style="border: solid 1px;">
    </div>  -->
    <div class="col-sm-4" id="col-sm-4-id" style="background-color: white;">
<!-- <p class="text-reight"> .col-sm-4<p> -->
    <p class="text-right" style="padding-top: 10px;">Супи<p>
        <p class="text-right">Основни ястия<p>

            <p class="text-right">Десерти<p>
                <p class="text-right">Аламинути<p>
                    <p class="text-right">Сандвичи<p>
                        <p class="text-right">Напитки<p>
    </div>



 

Newmenu/newmenu/app/views/layouts/_page_content.html.erb
  
  <!--   <div class="col-sm-8" style="border: solid 1px;">

      
        
      -->
      <!-- <div class="col-sm-8" style="border: solid 1px;">
    </div>  -->
    <div class="col-sm-4" id="col-sm-4-id" style="background-color: white;">
<!-- <p class="text-reight"> .col-sm-4<p> -->
	<p class="text-center" style=" border-bottom: 1px solid black;">Поръчка<p>
    <%  @order_items.each do |current_order_item| %>
     <%  @current_products.each do |current_product| %>
      <% if(current_product.id ==current_order_item.product_id) %>
      <% current_product_order_items_id_del  = @items_array[@counter_del] %>
          <% @counter_del=@counter_del+1 %>
		<p class="text-left" > <%= current_product.name%> | Бр. <%= current_order_item.quantity %>&nbsp<%= link_to "+",{:controller => :home,:action =>'update',:product_price => current_product.price,
      :order_item_id_update => current_order_item.id,:add => current_order_item.quantity},data: {confirm: 'Сигурни ли сте че искате да увеличите  количеството?'}  %> 






      |&nbsp <%= link_to "-",{:controller => :home,:action =>'update',:product_price => current_product.price,
        :order_item_id_update => current_order_item.id,:less => current_order_item.quantity },data: {confirm: 'Сигурни ли сте че искате да намалите  количеството?'}  %>




      &nbsp|&nbsp  <%= link_to "X",{:controller => :home,:action => 'destroy',:id => current_product.id ,:current_product_order_items_id =>  current_product_order_items_id_del} ,data: {confirm: 'Сигурни ли сте че искате да откажете тази поръчка?'} %><p>
  
         <% end %>
           <% end %>
           <% end %>

						<p class="text-left" style=" border-top: 1px solid black;"> Цена:  <%=    number_with_precision(@sum, :precision => 2) %> лв. <p>


   

Newmenu/newmenu/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newmenu</title>
    <%= csrf_meta_tags %>

 <%= javascript_include_tag 'application','jquery', 'data-turbolinks-track' => true  %>
       <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
     <%= csrf_meta_tags %>
   <!--   <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script> -->
     <!--   <script src="../../app/assets/javascript/jquery.min.js"></script>
<script src="../../app/assets/javascript/bootstrap.min.js"></script> -->
<!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script> -->
  </head>

  <body>
    <% if user_signed_in? %>
    <%= render 'layouts/header' %>
   <div class="container" >
             <!-- <p> Hello, <%= current_user.name %> - <%= link_to "Sign_out", destroy_user_session_path, :method => 'delete' %> </p> -->
             <br>
   
      <div class="wrapper" >
          <div class="row" >

     <div class="column col-xs-9" id="main" > <% end %>
   <%= yield %>
    </div>
       <% if user_signed_in? %>
    <div class="column col-xs-3" id="sidebar" >
      <%= render 'layouts/page_content' %>
    <%= render 'layouts/menu_content' %>
    </div><% end %>
  </div>
 </div>
</div>

   </body>
</html>

Newmenu/newmenu/app/views/meetings/_form.html.erb
<%= form_with(model: meeting, local: true) do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :meeting_name %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time, id: :meeting_start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time, id: :meeting_end_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Newmenu/newmenu/app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

Newmenu/newmenu/app/views/meetings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Meetings</h1>
<%= month_calendar events: @meetings do |date, meetings| %>
  <%= date %>

  <% meetings.each do |meeting| %>
    <div>
      <%= meeting.name %>
    </div>
  <% end %>
<% end %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= meeting.name %></td>
        <td><%= meeting.start_time %></td>
        <td><%= meeting.end_time %></td>
        <td><%= link_to 'Show', meeting %></td>
        <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
        <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<br>

<%= link_to 'New Meeting', new_meeting_path %>

Newmenu/newmenu/app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Back', meetings_path %>

Newmenu/newmenu/app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meeting.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @meeting.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @meeting.end_time %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>

Newmenu/newmenu/app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '<'), calendar.url_for_previous_view ,:controller => :home,:action => 'index',:start_date => params[:start_date] %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: '>'), calendar.url_for_next_view,:controller => :home,:action => 'index',:start_date => params[:start_date] %>

  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day), id: day do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day.strftime("%d"), sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>